# Generated by Django 3.1.2 on 2021-05-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0284_auto_20210507_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendsms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.BigIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=755, null=True)),
            ],
        ),
    ]
