# Generated by Django 3.1.2 on 2021-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0285_sendsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='Branchname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
