# Generated by Django 3.2.3 on 2021-05-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0287_sendanemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailydataExcelupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('Shift', models.CharField(max_length=255, null=True)),
                ('CenterCode', models.CharField(blank=True, max_length=255, null=True)),
                ('MilkType', models.CharField(max_length=255, null=True)),
                ('Good_Sour', models.CharField(blank=True, max_length=255, null=True)),
                ('SampleNo', models.FloatField(blank=True, default=0.0, null=True)),
                ('Cans', models.FloatField(blank=True, default=0.0, null=True)),
                ('Kgs', models.FloatField(default=0.0, null=True)),
                ('Fat', models.FloatField(default=0.0, null=True)),
                ('SNF', models.FloatField(default=0.0, null=True)),
                ('CLR', models.FloatField(default=0.0, null=True)),
                ('TSRATE', models.FloatField(blank=True, default=0.0, null=True)),
                ('Rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('comm', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
