# Generated by Django 3.2.3 on 2021-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0288_dailydataexcelupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokQC_Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sour', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('cans', models.IntegerField(default=0)),
                ('fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('clr', models.FloatField(blank=True, default=0.0, null=True)),
                ('snf', models.FloatField(blank=True, default=0.0, null=True)),
                ('routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
                ('samplecode', models.CharField(blank=True, max_length=255, null=True)),
                ('branch1', models.CharField(blank=True, max_length=255, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('shift1', models.CharField(blank=True, max_length=255, null=True)),
                ('code1', models.CharField(blank=True, max_length=255, null=True)),
                ('center_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type1', models.CharField(blank=True, max_length=255, null=True)),
                ('sour1', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity1', models.FloatField(blank=True, default=0.0, null=True)),
                ('cans1', models.IntegerField(default=0)),
                ('routecode1', models.CharField(blank=True, max_length=255, null=True)),
                ('remove1', models.CharField(blank=True, max_length=255, null=True)),
                ('samplecode1', models.CharField(blank=True, max_length=255, null=True)),
                ('fat1', models.FloatField(blank=True, default=0.0, null=True)),
                ('clr1', models.FloatField(blank=True, default=0.0, null=True)),
                ('snf1', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DokQC_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sour', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('cans', models.IntegerField(blank=True, default=0, null=True)),
                ('routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
                ('samplecode', models.IntegerField(default=0)),
                ('fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('clr', models.FloatField(blank=True, default=0.0, null=True)),
                ('snf', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
