# Generated by Django 3.1.3 on 2021-05-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0289_dokqc_create_dokqc_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokqc_create',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_create',
            name='creeated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lccrreatee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dokqc_create',
            name='updatedt_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uipdate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dokqc_create',
            name='updatee',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
