# Generated by Django 3.1.3 on 2021-05-20 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0290_auto_20210520_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logdokqc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('samplecode', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('cans', models.IntegerField(default=0)),
                ('fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('clr', models.FloatField(blank=True, default=0.0, null=True)),
                ('snf', models.FloatField(blank=True, default=0.0, null=True)),
                ('samplecode1', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity1', models.FloatField(blank=True, default=0.0, null=True)),
                ('cans1', models.IntegerField(default=0)),
                ('fat1', models.FloatField(blank=True, default=0.0, null=True)),
                ('clr1', models.FloatField(blank=True, default=0.0, null=True)),
                ('snf1', models.FloatField(blank=True, default=0.0, null=True)),
                ('creeated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updatedt_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updatee', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
