# Generated by Django 3.2.3 on 2021-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0293_remove_logdokqc_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokqc_entry',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='centername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='comm',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='ltrrate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='ltrs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='ltrtsrate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='net',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='pel',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='routename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dokqc_entry',
            name='tsrate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
