# Generated by Django 3.2.3 on 2021-05-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0294_auto_20210522_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokqc_entry',
            old_name='centername',
            new_name='centercode',
        ),
        migrations.RemoveField(
            model_name='dokqc_entry',
            name='code',
        ),
    ]
