# Generated by Django 3.2.3 on 2021-05-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0295_auto_20210522_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokqc_entry',
            name='clr',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='dokqc_entry',
            name='fat',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='dokqc_entry',
            name='snf',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
