# Generated by Django 3.2.3 on 2021-05-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0296_auto_20210522_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokqc_create',
            name='clr',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='dokqc_create',
            name='fat',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='dokqc_create',
            name='snf',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
