# Generated by Django 3.2 on 2021-05-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0299_auto_20210522_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdokqc',
            name='code1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logdokqc',
            name='remove1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
