# Generated by Django 3.2 on 2021-05-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0300_auto_20210524_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
