# Generated by Django 3.1.3 on 2021-05-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0302_auto_20210525_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
    ]
