# Generated by Django 3.2 on 2021-06-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0303_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='branch',
            new_name='BankBranch',
        ),
    ]
