# Generated by Django 3.2 on 2021-06-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0304_rename_branch_center_bankbranch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='branch1',
            new_name='BankBranch1',
        ),
    ]
