# Generated by Django 3.2 on 2021-06-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0305_rename_branch1_center_bankbranch1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_bankwise',
            old_name='branch',
            new_name='BankBranch',
        ),
    ]
