# Generated by Django 3.2 on 2021-06-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0306_rename_branch_rpt_bankwise_bankbranch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_excel_bankwise',
            old_name='branch',
            new_name='BankBranch',
        ),
    ]
