# Generated by Django 3.2 on 2021-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0307_rename_branch_rpt_excel_bankwise_bankbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_bankwise',
            name='cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_branch',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
