# Generated by Django 3.2 on 2021-06-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0309_remove_dashboard_branch_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_bankwise',
            name='cid',
        ),
    ]
