# Generated by Django 3.2 on 2021-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0310_remove_rpt_bankwise_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_branch',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
