# Generated by Django 3.2.3 on 2021-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0311_dashboard_branch_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_bankwise',
            name='NetAmt',
            field=models.FloatField(default=0.0),
        ),
    ]
