# Generated by Django 3.2.3 on 2021-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0312_rpt_bankwise_netamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_bankwise',
            name='NetAmt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
