# Generated by Django 3.2 on 2021-06-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0313_auto_20210616_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbillsdata',
            name='routecode',
        ),
        migrations.RemoveField(
            model_name='loanbillsdata',
            name='sdate',
        ),
        migrations.AddField(
            model_name='loanbillsdata',
            name='installment_principle_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='loanbillsdata',
            name='loanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.cloan'),
        ),
    ]
