# Generated by Django 3.2 on 2021-06-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0315_auto_20210618_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloan',
            name='Flat',
        ),
    ]
