# Generated by Django 3.2 on 2021-06-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0316_remove_cloan_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloan',
            old_name='billing',
            new_name='billperiod',
        ),
    ]
