# Generated by Django 3.2 on 2021-06-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0318_rpt_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_loan',
            name='date',
        ),
    ]
