# Generated by Django 3.2 on 2021-06-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0326_rpt_loan_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rpt_loan',
        ),
    ]
