# Generated by Django 3.2 on 2021-06-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0327_delete_rpt_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='rpt_loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('loan_no', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('noofinstallments', models.IntegerField(blank=True, null=True)),
                ('billperiod', models.FloatField(blank=True, default=0.0, null=True)),
                ('flat_deminished', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('principal_amt', models.IntegerField(blank=True, null=True)),
                ('interest_amt', models.FloatField(blank=True, default=0.0, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('outstandingamount', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
