# Generated by Django 3.2 on 2021-06-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0328_rpt_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rpt_loan',
        ),
    ]
