# Generated by Django 3.2 on 2021-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0330_rpt_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_loan',
            name='outstandingamount',
        ),
        migrations.AddField(
            model_name='rpt_loan',
            name='closingdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
