# Generated by Django 3.2 on 2021-06-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0331_auto_20210619_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_loan',
            name='outstandingamount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
