# Generated by Django 3.2 on 2021-06-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0332_rpt_loan_outstandingamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_loan',
            name='date',
        ),
    ]
