# Generated by Django 3.2 on 2021-06-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0333_remove_rpt_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_loan',
            name='installment_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
