# Generated by Django 3.2 on 2021-06-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0336_rpt_loan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_loan',
            old_name='principal_amt',
            new_name='installment_principle_amt',
        ),
    ]
