# Generated by Django 3.2 on 2021-06-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0338_rename_installment_principle_amt_rpt_loan_principal_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_loan',
            old_name='principal_amt',
            new_name='installment_principle_amt',
        ),
    ]
