# Generated by Django 3.2 on 2021-06-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0339_rename_principal_amt_rpt_loan_installment_principle_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractPlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blkCode', models.CharField(blank=True, max_length=10, null=True)),
                ('treeNo', models.FloatField(default=0.0, null=True)),
                ('plantDate', models.DateField(blank=True, null=True)),
                ('plantType', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.FloatField(blank=True, default=0.0, null=True)),
                ('girth', models.FloatField(blank=True, default=0.0, null=True)),
                ('leaveCnt', models.IntegerField(blank=True, null=True)),
                ('tcWeeType', models.CharField(blank=True, max_length=10, null=True)),
                ('tcWaterlog', models.CharField(blank=True, max_length=10, null=True)),
                ('tcMud', models.CharField(blank=True, max_length=10, null=True)),
                ('TCNet', models.CharField(blank=True, max_length=10, null=True)),
                ('WTRing', models.CharField(blank=True, max_length=10, null=True)),
                ('Waterpipe', models.CharField(blank=True, max_length=10, null=True)),
                ('PnDFung', models.CharField(blank=True, max_length=10, null=True)),
                ('PNDTermite', models.CharField(blank=True, max_length=10, null=True)),
                ('PNDChType', models.CharField(blank=True, max_length=10, null=True)),
                ('PNDDate', models.DateField(blank=True, null=True)),
                ('manurFType', models.CharField(blank=True, max_length=10, null=True)),
                ('ManureRate', models.FloatField(blank=True, default=0.0, null=True)),
                ('ManureDate', models.DateField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
