# Generated by Django 3.2 on 2021-06-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0340_extractplantdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydataexcelupload',
            name='file_name',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
