# Generated by Django 3.2 on 2021-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0341_dailydataexcelupload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydataexcelupload',
            name='file_name',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
