# Generated by Django 3.2 on 2021-06-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0342_alter_dailydataexcelupload_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydataexcelupload',
            name='file_name',
        ),
    ]
