# Generated by Django 3.2 on 2021-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0343_remove_dailydataexcelupload_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydataexcelupload',
            name='file_name',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
