# Generated by Django 3.2 on 2021-06-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0346_alter_dailydataexcelupload_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractplantdata',
            name='areaCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='extractplantdata',
            name='teraceNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
