# Generated by Django 3.2 on 2021-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0347_auto_20210630_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractplantdata',
            name='treeNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
