# Generated by Django 3.2 on 2021-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0348_alter_extractplantdata_treeno'),
    ]

    operations = [
        migrations.CreateModel(
            name='rpt_emsDeDSumbyAnB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(blank=True, max_length=10, null=True)),
                ('blkCode', models.CharField(blank=True, max_length=10, null=True)),
                ('DedCnt', models.IntegerField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rpt_emsSumbyAnB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(blank=True, max_length=10, null=True)),
                ('blkCode', models.CharField(blank=True, max_length=10, null=True)),
                ('teraceNo', models.CharField(blank=True, max_length=10, null=True)),
                ('treeNo', models.IntegerField(blank=True, default=0.0, null=True)),
                ('plantDate', models.DateField(blank=True, null=True)),
                ('plantType', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.FloatField(blank=True, default=0.0, null=True)),
                ('TotCnt', models.IntegerField(blank=True, default=0.0, null=True)),
                ('DedCnt', models.IntegerField(blank=True, default=0.0, null=True)),
                ('LivCnt', models.IntegerField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
