# Generated by Django 3.0.4 on 2021-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0349_rpt_emsdedsumbyanb_rpt_emssumbyanb'),
    ]

    operations = [
        migrations.CreateModel(
            name='rpt_emsSumTH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(blank=True, max_length=10, null=True)),
                ('blkCode', models.CharField(blank=True, max_length=10, null=True)),
                ('treeCnt', models.IntegerField(blank=True, default=0.0, null=True)),
                ('aHeight', models.FloatField(blank=True, default=0.0, null=True)),
                ('aGirth', models.FloatField(blank=True, default=0.0, null=True)),
                ('aLeaves', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rpt_emssumbyanb',
            name='height',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumbyanb',
            name='plantDate',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumbyanb',
            name='plantType',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumbyanb',
            name='teraceNo',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumbyanb',
            name='treeNo',
        ),
    ]
