# Generated by Django 3.0.4 on 2021-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0351_auto_20210707_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proc_Data_EE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecNo', models.FloatField(blank=True, default=0.0, null=True)),
                ('PDate', models.DateField(blank=True, null=True)),
                ('Shift', models.CharField(max_length=255, null=True)),
                ('MilkType', models.CharField(max_length=255, null=True)),
                ('CenterCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Kgs', models.FloatField(default=0.0, null=True)),
                ('Fat', models.FloatField(default=0.0, null=True)),
                ('CLR', models.FloatField(default=0.0, null=True)),
                ('SNF', models.FloatField(default=0.0, null=True)),
                ('Cans', models.FloatField(blank=True, default=0.0, null=True)),
                ('Filename', models.CharField(max_length=255, null=True)),
                ('ExtUser', models.CharField(blank=True, max_length=255, null=True)),
                ('ExtDate', models.DateField(blank=True, null=True)),
                ('ValidData', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vercode', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('vername', models.CharField(blank=True, max_length=255, null=True)),
                ('effectedfromdate', models.DateField(blank=True, null=True)),
                ('effectedtodate', models.DateField(blank=True, null=True)),
                ('createdby', models.CharField(blank=True, max_length=255, null=True)),
                ('editedby', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch1',
            name='active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch1',
            name='active1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branchlog',
            name='active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branchlog',
            name='active1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='datefrom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='dateto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
