# Generated by Django 3.0.4 on 2021-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0352_auto_20210709_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractplantdata',
            name='fileName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
