# Generated by Django 3.0.4 on 2021-07-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0355_emsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='emsdata',
            name='FrDUP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='IVDate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='IVGirth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='IVHeight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='IVLeave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='IVType',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='PrDUP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='validRec',
            field=models.BooleanField(default=True),
        ),
    ]
