# Generated by Django 3.0.4 on 2021-07-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0356_auto_20210710_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EMSData',
            new_name='Rpt_EMSData',
        ),
    ]
