# Generated by Django 3.0.4 on 2021-07-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0357_auto_20210710_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSPlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PType', models.CharField(max_length=10, unique=True)),
                ('Desc', models.CharField(max_length=100, unique=True)),
                ('remove', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
