# Generated by Django 3.0.4 on 2021-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0361_auto_20210711_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(max_length=10, unique=True)),
                ('areaName', models.CharField(max_length=100, unique=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('remove', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMSBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blkCode', models.CharField(max_length=10, unique=True)),
                ('BlkName', models.CharField(max_length=100, unique=True)),
                ('noOfTeraces', models.IntegerField(blank=True, null=True)),
                ('noOfTrees', models.IntegerField(blank=True, null=True)),
                ('gpdCoOd', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.FloatField(blank=True, default=0.0, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('remove', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
