# Generated by Django 3.0.4 on 2021-07-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0362_emsarea_emsblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_emsrevsim',
            old_name='ManureDate',
            new_name='YAmt1',
        ),
        migrations.RenameField(
            model_name='rpt_emsrevsim',
            old_name='PNDDate',
            new_name='YMth1',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='PNDChType',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='PNDTermite',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='PnDFung',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='TCNet',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='WTRing',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='Waterpipe',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='manurFType',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='tcMud',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='tcWaterlog',
        ),
        migrations.RemoveField(
            model_name='rpt_emsrevsim',
            name='tcWeeType',
        ),
        migrations.AddField(
            model_name='rpt_emsrevsim',
            name='NutMatrCost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emsrevsim',
            name='YProd1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emsrevsim',
            name='YieldEndAge',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emsrevsim',
            name='YieldIncrPer',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='NutsEst',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
    ]
