# Generated by Django 3.0.4 on 2021-07-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0363_auto_20210713_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='YAmt1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='YProd1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
