# Generated by Django 3.0.4 on 2021-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0364_auto_20210713_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='emsplanttype',
            name='NutFrCost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='emsplanttype',
            name='NutMatrCost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='emsplanttype',
            name='YieldEndAge',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
        migrations.AddField(
            model_name='emsplanttype',
            name='YieldIncrPer',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='emsplanttype',
            name='YieldStAge',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
        migrations.AddField(
            model_name='emsplanttype',
            name='nutvcocost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
