# Generated by Django 3.0.4 on 2021-07-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0365_auto_20210713_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='NutVcoCost',
            field=models.FloatField(default=0.0),
        ),
    ]
