# Generated by Django 3.0.4 on 2021-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0366_auto_20210714_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='NutMatrCost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='extUser',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='extdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='fileName',
            field=models.CharField(max_length=50),
        ),
    ]
