# Generated by Django 3.0.4 on 2021-07-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0367_auto_20210714_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='NutMatrCost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='NutVcoCost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='extUser',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='extdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_emsrevsim',
            name='fileName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
