# Generated by Django 3.0.4 on 2021-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0368_auto_20210714_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='emsplanttype',
            name='EstNuts',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='emsplanttype',
            name='YieldEndAge',
            field=models.IntegerField(blank=True, default=180, null=True),
        ),
        migrations.AlterField(
            model_name='emsplanttype',
            name='YieldIncrPer',
            field=models.FloatField(blank=True, default=20, null=True),
        ),
    ]
