# Generated by Django 3.2 on 2021-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0369_auto_20210714_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centermasterdataexcelupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cCode', models.CharField(blank=True, max_length=255, null=True)),
                ('rCODE', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('cName', models.CharField(blank=True, max_length=255, null=True)),
                ('aName', models.CharField(blank=True, max_length=255, null=True)),
                ('vName', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('bankno', models.CharField(blank=True, max_length=255, null=True)),
                ('bkCode', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ifscexcelupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNO', models.FloatField(blank=True, max_length=255, null=True)),
                ('BKCODE', models.CharField(blank=True, max_length=255, null=True)),
                ('IFSC', models.CharField(blank=True, max_length=255)),
                ('BKNAME', models.CharField(blank=True, max_length=255, null=True)),
                ('CITY', models.CharField(max_length=255, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('FILE_NAME', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tsratesexcelupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_From', models.DateField(blank=True, max_length=255, null=True)),
                ('Date_To', models.DateField(blank=True, max_length=255, null=True)),
                ('Min_Fat', models.FloatField(blank=True, max_length=255, null=True)),
                ('Max_Fat', models.FloatField(blank=True, max_length=255, null=True)),
                ('Min_SNF', models.FloatField(max_length=255, null=True)),
                ('Max_SNF', models.FloatField(blank=True, max_length=255, null=True)),
                ('Unit', models.CharField(blank=True, max_length=255, null=True)),
                ('TSRATE', models.FloatField(blank=True, max_length=255, null=True)),
                ('FILE_NAME', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
