# Generated by Django 3.0.4 on 2021-07-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0371_extractplantdata_censusdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumth',
            name='teraceNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
