# Generated by Django 3.0.4 on 2021-07-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0372_rpt_emssumth_teraceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emsdedsumbyanb',
            name='teraceNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
