# Generated by Django 3.0.4 on 2021-07-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0373_rpt_emsdedsumbyanb_teraceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumbyanb',
            name='teraceNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
