# Generated by Django 3.0.4 on 2021-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0374_rpt_emssumbyanb_teraceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emsrevsim',
            name='YMthNo',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
    ]
