# Generated by Django 3.0.4 on 2021-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0375_rpt_emsrevsim_ymthno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpt_EMSRevSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(blank=True, max_length=10, null=True)),
                ('blkCode', models.CharField(blank=True, max_length=10, null=True)),
                ('teraceNo', models.CharField(blank=True, max_length=10, null=True)),
                ('plantDate', models.DateField(blank=True, null=True)),
                ('plantType', models.CharField(blank=True, max_length=10, null=True)),
                ('TreesCnt', models.IntegerField(blank=True, null=True)),
                ('YNuts', models.FloatField(blank=True, default=0.0, null=True)),
                ('YYear', models.IntegerField(blank=True, default=48, null=True)),
                ('YMth', models.IntegerField(blank=True, default=48, null=True)),
                ('YAmt', models.FloatField(blank=True, default=0.0, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
