# Generated by Django 3.2 on 2021-07-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0377_auto_20210726_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticecode', models.CharField(max_length=25, unique=True)),
                ('noticename', models.CharField(blank=True, max_length=256, null=True)),
                ('effectedfromdate', models.DateField(blank=True, null=True)),
                ('effectedtodate', models.DateField(blank=True, null=True)),
                ('createdby', models.CharField(blank=True, max_length=255, null=True)),
                ('editedby', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('editedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
