# Generated by Django 3.2 on 2021-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0379_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HCode', models.CharField(max_length=255, unique=True)),
                ('TreeHeight', models.FloatField(blank=True, max_length=255, null=True)),
                ('Duration', models.FloatField(blank=True, max_length=255, null=True)),
                ('TimePerTree', models.FloatField(blank=True, max_length=255, null=True)),
                ('NoOfNuts', models.FloatField(blank=True, max_length=255, null=True)),
                ('IncrPer', models.FloatField(blank=True, max_length=255, null=True)),
                ('HStAge', models.IntegerField(blank=True, default=200, null=True)),
                ('HEndAge', models.IntegerField(blank=True, default=200, null=True)),
            ],
        ),
    ]
