# Generated by Django 3.2 on 2021-08-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0380_harvesting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSFertiliser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FType', models.CharField(max_length=10, unique=True)),
                ('FName', models.CharField(max_length=100, unique=True)),
                ('remove', models.CharField(blank=True, max_length=5, null=True)),
                ('FCost', models.FloatField(blank=True, default=0.0, null=True)),
                ('QtyPerTree', models.FloatField(blank=True, default=20, null=True)),
                ('FreqPerTree', models.FloatField(blank=True, default=0.0, null=True)),
                ('IncrPer', models.IntegerField(blank=True, default=20, null=True)),
                ('FStAge', models.IntegerField(blank=True, default=48, null=True)),
                ('FEndAge', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
    ]
