# Generated by Django 3.2 on 2021-08-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0381_emsfertiliser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icode', models.CharField(max_length=255, unique=True)),
                ('Block', models.CharField(max_length=255, unique=True)),
                ('Pump', models.CharField(blank=True, max_length=255, null=True)),
                ('Duration', models.FloatField(blank=True, max_length=255, null=True)),
                ('Qtypertree', models.FloatField(blank=True, max_length=255, null=True)),
                ('Freqofpumping', models.FloatField(blank=True, max_length=255, null=True)),
                ('Fuelcostperhour', models.FloatField(blank=True, max_length=255, null=True)),
                ('Incrper', models.FloatField(blank=True, max_length=255, null=True)),
                ('Istage', models.IntegerField(blank=True, default=100, null=True)),
                ('Iendage', models.IntegerField(blank=True, default=180, null=True)),
            ],
        ),
    ]
