# Generated by Django 3.2 on 2021-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0382_irrigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSPND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PType', models.CharField(max_length=10, unique=True)),
                ('PName', models.CharField(max_length=100, unique=True)),
                ('remove', models.CharField(blank=True, max_length=5, null=True)),
                ('PCost', models.FloatField(blank=True, default=0.0, null=True)),
                ('QtyPerTree', models.FloatField(blank=True, default=20, null=True)),
                ('FreqOfSpray', models.FloatField(blank=True, default=0.0, null=True)),
                ('IncrPer', models.FloatField(blank=True, default=20, null=True)),
                ('PStAge', models.IntegerField(blank=True, default=48, null=True)),
                ('PEndAge', models.IntegerField(blank=True, default=180, null=True)),
            ],
        ),
    ]
