# Generated by Django 3.0.4 on 2021-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0384_rpt_emssumbyanbonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumbyanbonly',
            name='treeNo',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
