# Generated by Django 3.0.4 on 2021-08-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0385_rpt_emssumbyanbonly_treeno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_emssumbyanbonly',
            old_name='treeNo',
            new_name='teraceNo',
        ),
    ]
