# Generated by Django 3.0.4 on 2021-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0386_auto_20210801_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumbyanb',
            name='cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumbyanb',
            name='eid',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumbyanbonly',
            name='eid',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
