# Generated by Django 3.0.4 on 2021-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0387_auto_20210803_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumbyanb',
            name='TeraceCnt',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
