# Generated by Django 3.0.4 on 2021-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0388_rpt_emssumbyanb_teracecnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_emssumbyanb',
            name='cid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
