# Generated by Django 3.0.4 on 2021-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0389_auto_20210804_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumbyanb',
            name='LivSum',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
