# Generated by Django 3.2 on 2021-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0390_rpt_emssumbyanb_livsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumth',
            name='cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumth',
            name='eid',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
