# Generated by Django 3.2 on 2021-08-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0391_auto_20210805_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_emssumth',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumth',
            name='eid',
        ),
    ]
