# Generated by Django 3.2 on 2021-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0396_alter_rpt_emssumth_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumth',
            name='LivSum',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumth',
            name='TeraceCnt',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
