# Generated by Django 3.2 on 2021-08-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0399_auto_20210806_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumth',
            name='terace',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
