# Generated by Django 3.0.4 on 2021-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0401_auto_20210808_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumth',
            name='teraceCnt',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
