# Generated by Django 3.0.4 on 2021-08-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0402_rpt_emssumth_teracecnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emssumth',
            name='girth',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumth',
            name='height',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumth',
            name='leaves',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumth',
            name='terace',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
