# Generated by Django 3.0.4 on 2021-08-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0403_auto_20210808_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpt_EMSRevSumO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantDate', models.DateField(blank=True, null=True)),
                ('TreesCnt', models.IntegerField(blank=True, null=True)),
                ('YNuts', models.FloatField(blank=True, default=0.0, null=True)),
                ('YYear', models.IntegerField(blank=True, default=48, null=True)),
                ('YMth', models.CharField(blank=True, max_length=15, null=True)),
                ('YAmt', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
