# Generated by Django 3.0.4 on 2021-08-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0404_rpt_emsrevsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_emsrevsumo',
            name='YPer',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
