# Generated by Django 3.2 on 2021-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0405_rpt_emsrevsumo_yper'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractplantdata',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
