# Generated by Django 3.2 on 2021-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0406_extractplantdata_remove'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSRFCEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(blank=True, max_length=10, null=True)),
                ('blkCode', models.CharField(blank=True, max_length=10, null=True)),
                ('teraceNo', models.CharField(blank=True, max_length=10, null=True)),
                ('treeCnt', models.IntegerField(blank=True, null=True)),
                ('plantDate', models.DateField(blank=True, null=True)),
                ('plantType', models.CharField(blank=True, max_length=10, null=True)),
                ('YieldStAge', models.IntegerField(blank=True, default=48, null=True)),
                ('YieldEndAge', models.IntegerField(blank=True, default=48, null=True)),
                ('NutsEst', models.IntegerField(blank=True, default=48, null=True)),
                ('NutFrCost', models.FloatField(blank=True, default=0.0, null=True)),
                ('NutVcoCost', models.FloatField(blank=True, default=0.0, null=True)),
                ('NutMatrCost', models.FloatField(blank=True, default=0.0, null=True)),
                ('YieldIncrPer', models.FloatField(blank=True, default=0.0, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('extdate', models.DateField(blank=True, null=True)),
                ('extUser', models.CharField(blank=True, max_length=255)),
                ('fileName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
