# Generated by Django 3.0.4 on 2021-08-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0407_emsrfcee'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractplantdata',
            name='TreeAge',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
