# Generated by Django 3.0.4 on 2021-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0410_rpt_emssumbyaonly'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSPlantTypeT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlantType', models.CharField(max_length=10, unique=True)),
                ('Description', models.CharField(max_length=100, unique=True)),
                ('FreshnutCost', models.FloatField(blank=True, default=0.0, null=True)),
                ('MatrednutCost', models.FloatField(blank=True, default=0.0, null=True)),
                ('EstNuts', models.IntegerField(blank=True, default=5, null=True)),
                ('VCOcost', models.FloatField(blank=True, default=0.0, null=True)),
                ('YieldStartAge', models.IntegerField(blank=True, default=48, null=True)),
                ('YieldEndAge', models.IntegerField(blank=True, default=180, null=True)),
                ('Increment', models.FloatField(blank=True, default=20, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
