# Generated by Django 3.0.4 on 2021-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0413_auto_20210824_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpt_ExtractPlantTHAgData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCode', models.CharField(blank=True, max_length=10, null=True)),
                ('blkCode', models.CharField(blank=True, max_length=10, null=True)),
                ('teraceNo', models.CharField(blank=True, max_length=10, null=True)),
                ('treeNo', models.IntegerField(blank=True, null=True)),
                ('plantDate', models.DateField(blank=True, null=True)),
                ('plantType', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.FloatField(blank=True, default=0.0, null=True)),
                ('girth', models.FloatField(blank=True, default=0.0, null=True)),
                ('leaveCnt', models.IntegerField(blank=True, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('extdate', models.DateField(blank=True, null=True)),
                ('fileName', models.CharField(blank=True, max_length=50, null=True)),
                ('censusdate', models.DateField(blank=True, null=True)),
                ('TreeAge', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
