# Generated by Django 3.0.4 on 2021-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0414_rpt_extractplantthagdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_emssumtharonly',
            old_name='DedCnt',
            new_name='blkCnt',
        ),
        migrations.RenameField(
            model_name='rpt_emssumtharonly',
            old_name='LivCnt',
            new_name='treeCnt',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumtharonly',
            name='TotCnt',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumtharonly',
            name='blkCode',
        ),
        migrations.AddField(
            model_name='rpt_emssumtharonly',
            name='aGirth',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumtharonly',
            name='aHeight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_emssumtharonly',
            name='aLeaves',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
