# Generated by Django 3.0.4 on 2021-08-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0416_auto_20210828_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_extractplantagdata',
            name='cid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantagdata',
            name='eid',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='LivSum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='TeraceCnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='blkCnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='cid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='eid',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
