# Generated by Django 3.0.4 on 2021-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0417_auto_20210828_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='aGirth',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='aHeight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='aLeaves',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
