# Generated by Django 3.0.4 on 2021-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0419_rpt_emssumbyh'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_extractplantthagdata',
            name='cidH',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
