# Generated by Django 3.2 on 2021-09-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0423_rpt_emssumbyaonly_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_emssumbyaonly',
            name='cid',
        ),
        migrations.AddField(
            model_name='rpt_emssumbyanbonly',
            name='cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
