# Generated by Django 3.2 on 2021-09-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0425_rpt_emssumbyaonly_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_emssumbyanbonly',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumbyaonly',
            name='cid',
        ),
    ]
