# Generated by Django 3.2 on 2021-09-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0427_auto_20210922_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_emssumbyanbonly',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='rpt_emssumbyaonly',
            name='cid',
        ),
    ]
